# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'memo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogMemo(object):
    def setupUi(self, DialogMemo):
        DialogMemo.setObjectName("DialogMemo")
        DialogMemo.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogMemo.resize(400, 300)
        self.textEditMemo = QtWidgets.QTextEdit(DialogMemo)
        self.textEditMemo.setGeometry(QtCore.QRect(20, 20, 361, 211))
        self.textEditMemo.setObjectName("textEditMemo")
        self.pushbutton_ok = QtWidgets.QPushButton(DialogMemo)
        self.pushbutton_ok.setGeometry(QtCore.QRect(310, 260, 75, 23))
        self.pushbutton_ok.setObjectName("pushbutton_ok")

        self.retranslateUi(DialogMemo)
        QtCore.QMetaObject.connectSlotsByName(DialogMemo)

    def retranslateUi(self, DialogMemo):
        _translate = QtCore.QCoreApplication.translate
        DialogMemo.setWindowTitle(_translate("DialogMemo", "Bemerkungen"))
        self.pushbutton_ok.setText(_translate("DialogMemo", "OK"))
